languageCode = "ja-jp"
baseurl = "https://cuboktahedron.github.io/"
title = "Ununique."
hasCJKLanguage = true

[Params]
author = "cuboktahedron"

[taxnomies]
tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
