name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Update theme
        run: git submodule update --init --recursive
        
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.64.0"

      - name: Build
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.MY_GITHUB_ACCESS_TOKEN }}
          external_repository: cuboktahedron/cuboktahedron.github.io
          publish_dir: ./public
          user_name: cuboktahedron
          user_email: cuboktahedron@email.com
          publish_branch: master
          full_commit_message: ${{ github.event.head_commit.message }}
